strictness: veryhigh
doc-warnings: no
test-warnings: yes
uses:
  - django
python-targets:
  - 2
  - 3
max-line-length: 120
pylint:
  disable:
    - too-many-ancestors
    - too-many-public-methods
    - invalid-name
