# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapobjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapobject',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
