# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapobjects', '0002_auto_20160426_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobject',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapobject',
            name='name',
            field=models.CharField(default='unbenannt', max_length=100),
        ),
    ]
