# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unbenannt', max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=100)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date', models.DateField()),
                ('repetition_cycle', models.CharField(default='unbekannter Rhythmus', max_length=50)),
                ('organizer', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
                ('counter_event', models.BooleanField(default=False)),
                ('coverage', models.BooleanField(default=False)),
                ('participants', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
