# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170103_1741'),
        ('twitter', '0002_hashtag_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='twitter_hashtags',
        ),
    ]
