# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 17:58
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
