# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 20:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170103_2022'),
        ('twitter', '0004_twitteraccount_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='twitter_account_names',
        ),
    ]
