# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 10:51
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
    ]
