# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_twitter_account_names'),
        ('events', '0005_event_notes'),
    ]

    operations = [
    ]
