# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 10:35
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_merge_20170106_1231'),
        ('events', '0006_event_internal_notes'),
    ]

    operations = [
    ]
