# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 16:59
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    """Add a view permission for User, Event and FacebookPage.

    Admins get all those new permissions, mods only those for Events and FacebookPages.
    """
    # We can't import the models directly as they may be newer versions than this migration expects.
    # We use the historical versions instead.
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Event = apps.get_model('events', 'Event')
    FacebookPage = apps.get_model('facebook', 'FacebookPage')

    db_alias = schema_editor.connection.alias

    admins = Group.objects.using(db_alias).get(name="Administratoren")
    mods   = Group.objects.using(db_alias).get(name="Moderatoren")

    for model in [User, Event, FacebookPage]:
        content_type = ContentType.objects.get_for_model(model)
        model_name = model.__name__.lower()
        permission = Permission.objects.create(
            codename='view_%s' % model_name,
            name='Can view %s' % model_name,
            content_type=content_type,
        )
        
        admins.permissions.add(permission)
        # mods shall not have any User-related permissions
        if model != User:
            mods.permissions.add(permission)


def reverse_func(apps, schema_editor):
    """Deletes view permission for User, Event and FacebookPage.

    Any assignments of these permissions are deleted as well.
    """
    User = apps.get_model('auth', 'User')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Event = apps.get_model('events', 'Event')
    FacebookPage = apps.get_model('facebook', 'FacebookPage')

    db_alias = schema_editor.connection.alias

    # Remove view permissions. Assigned permissions are deleted automatically.
    for model in [User, Event, FacebookPage]:
        content_type = ContentType.objects.get_for_model(model)
        Permission.objects.using(db_alias).filter(content_type=content_type, codename__contains='view').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
