# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 14:56
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


def add_group_permissions(apps, schema_editor):
    admins = Group.objects.get(name="Administratoren")
    mods = Group.objects.get(name="Moderatoren")
    cts = ContentType.objects.filter(app_label='blog')
    perms = Permission.objects.filter(content_type__in=cts)
    admins.permissions.add(*perms)
    mods.permissions.add(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160813_1659'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
