# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapobjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('mapobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mapobjects.MapObject')),
                ('date', models.DateField()),
                ('repetition_cycle', models.CharField(max_length=50)),
                ('organizer', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('link_to_event', models.URLField()),
                ('counter_event', models.BooleanField()),
                ('coverage', models.BooleanField()),
            ],
            bases=('mapobjects.mapobject',),
        ),
    ]
