# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='counter_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='link_to_event',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='repetition_cycle',
            field=models.CharField(default='unbekannter Rhythmus', max_length=50),
        ),
    ]
