# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 14:38
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('addresses', models.TextField(editable=False)),
            ],
        ),
    ]
