# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 15:28
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20160919_1550'),
        ('facebook', '0002_auto_20160927_1528'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published'), ('HIDDEN', 'hidden')], default='DRAFT', max_length=15)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('events', models.ManyToManyField(blank=True, related_name='blog_entries', to='events.Event')),
                ('facebook_pages', models.ManyToManyField(blank=True, related_name='blog_entries', to='facebook.FacebookPage')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
