# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapobjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookLikeStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('like_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('mapobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mapobjects.MapObject')),
                ('link_to_facebook', models.URLField()),
            ],
            bases=('mapobjects.mapobject',),
        ),
    ]
