# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='events',
            field=models.ManyToManyField(to='events.Event'),
        ),
    ]
