# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_facebookpage_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklikestatistic',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook.FacebookPage'),
        ),
    ]
