# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_facebooklikestatistic_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='events',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
