# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 20:38
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_hashtag_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='account_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
