# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='facebook_pages', to='events.Event'),
        ),
    ]
