# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 10:51
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20160928_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
    ]
